import { GoogleGenerativeAI } from "@google/generative-ai";
import { NextResponse } from "next/server";

// Timeout wrapper for promises
const withTimeout = <T>(promise: Promise<T>, timeoutMs: number): Promise<T> => {
  const timeout = new Promise<never>((_, reject) =>
    setTimeout(() => reject(new Error(`Operation timed out after ${timeoutMs}ms`)), timeoutMs)
  );
  return Promise.race([promise, timeout]);
};

export async function POST(req: Request) {
  try {
    const apiKey = process.env.GEMINI_API_KEY;

    console.log("API key length:", apiKey ? apiKey.length : 0);
    console.log(
      "API key first 4 chars:",
      apiKey ? apiKey.substring(0, 4) : "none"
    );

    if (!apiKey) {
      return NextResponse.json(
        { error: "API key is not configured" },
        { status: 500 }
      );
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const reqData = await req.json();
    const { prompt, width, height } = reqData;
    
    const imagePrompt =
      prompt ||
      "Create a 3D birthday card with colorful balloons and confetti";

    console.log(`Requested dimensions: ${width}x${height}`);

    try {
      const model = genAI.getGenerativeModel({
        model: "gemini-2.0-flash-exp-image-generation",
      });

      // Wrap the generation in a timeout
      const response = await withTimeout(
        model.generateContent(imagePrompt),
        90000 // 90 second timeout
      );

      let generatedText = "";
      let imageData = null;

      if (response.response?.candidates?.[0]?.content?.parts) {
        for (const part of response.response.candidates[0].content.parts) {
          if (part.text) {
            generatedText = part.text;
          } else if (part.inlineData) {
            imageData = part.inlineData.data;
          }
        }
      }

      if (!imageData) {
        throw new Error("No image generated by Gemini");
      }

      return new NextResponse(
        JSON.stringify({
          imageData: imageData,
          generatedText: generatedText,
        }),
        {
          status: 200,
          headers: {
            'Content-Type': 'application/json',
          },
        }
      );

    } catch (error) {
      console.error("Generation error:", error);

      // Check for timeout
      if (error instanceof Error && error.message.includes("timed out")) {
        return new NextResponse(
          JSON.stringify({
            error: "Image generation timed out. Please try again.",
            details: error.message,
          }),
          {
            status: 504,
            headers: {
              'Content-Type': 'application/json',
            },
          }
        );
      }

      // Fallback to Pollinations if model not available
      if (
        error instanceof Error &&
        (error.message.includes("not found") ||
          error.message.includes("not supported"))
      ) {
        try {
          const textModel = genAI.getGenerativeModel({ model: "gemini-pro" });
          const textResult = await withTimeout(
            textModel.generateContent(imagePrompt),
            30000 // 30 second timeout for text
          );
          const text = textResult.response.text();

          if (!text) {
            throw new Error("No text response from Gemini");
          }

          const baseUrl = "https://image.pollinations.ai/prompt/";
          const params = new URLSearchParams({
            width: width?.toString() || "1080",
            height: height?.toString() || "1080",
            seed: Math.floor(Math.random() * 1000000).toString(),
            model: "flux",
            nologo: "true",
          });

          const enhancedPrompt = encodeURIComponent(text);
          const imageUrl = `${baseUrl}${enhancedPrompt}?${params.toString()}`;

          return new NextResponse(
            JSON.stringify({
              imageUrl: imageUrl,
              generatedText: text,
              fallback: true,
            }),
            {
              status: 200,
              headers: {
                'Content-Type': 'application/json',
              },
            }
          );
        } catch (fallbackError) {
          console.error("Fallback error:", fallbackError);
          return new NextResponse(
            JSON.stringify({
              error: "Fallback image generation failed",
              details: fallbackError instanceof Error ? fallbackError.message : "Unknown error",
            }),
            {
              status: 400,
              headers: {
                'Content-Type': 'application/json',
              },
            }
          );
        }
      }

      // General error handling
      return new NextResponse(
        JSON.stringify({
          error: "Failed to generate image",
          details: error instanceof Error ? error.message : "Unknown error",
        }),
        {
          status: 400,
          headers: {
            'Content-Type': 'application/json',
          },
        }
      );
    }
  } catch (error) {
    console.error("Outer error:", error);
    return new NextResponse(
      JSON.stringify({
        error: "Server error",
        details: error instanceof Error ? error.message : "Unknown error",
      }),
      {
        status: 500,
        headers: {
          'Content-Type': 'application/json',
        },
      }
    );
  }
}
